source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TEFMDBManage_Example', :exclusive => true do
  pod 'TEFMDBManage', :path => '../'
end

target 'TEFMDBManage_Tests', :exclusive => true do
  pod 'TEFMDBManage', :path => '../'

  
end
